# Generated by Django 5.2.1 on 2025-06-03 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_delete_place_delete_teammember_supportmember_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supportmember',
            name='email',
        ),
        migrations.RemoveField(
            model_name='supportmember',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='supportmember',
            name='role',
        ),
    ]
