# Generated by Django 5.2.1 on 2025-06-04 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_remove_supportmember_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('image', models.ImageField(upload_to='places/')),
                ('description', models.TextField()),
                ('category', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='Places',
        ),
        migrations.AddField(
            model_name='supportmember',
            name='role',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
