# Generated by Django 5.2.1 on 2025-06-04 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_place_delete_places_supportmember_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='address',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
